### ISSUE TITLE
About how to manage this hello files

### ISSUE THREAD

**Issue by amlinus** [anemele/helloworld#3]
Now, the hello programs in various language are listed in the same directory, and can be only read but not executed.
How about add something to manage these files?
Well, I have no idea yet.

**Comment by anemele** [comment]
I have thought about this problem, and I wrote a makefile to compile and run hello programs written in compiled language like C/C++. But it failed me.
Then I realized that the best compiler/interpreter is the brain. On the other hand, so short as a hello program is that it really do not be run by the machine.
